# Generated by Django 4.2 on 2023-06-12 15:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('cantidad_de_personas', models.IntegerField()),
                ('dificultad', models.CharField(blank=True, choices=[('preparacion facil', 'Preparacion Facil'), ('preparacion intermedia', 'Preparacion Intermedia'), ('preparacion avanzada', 'Preparacion Avanzada')], default='preparacion facil', max_length=40, null=True)),
                ('imagenp', models.ImageField(blank=True, null=True, upload_to='postres')),
                ('informacion_adicional', ckeditor.fields.RichTextField()),
                ('receta', models.FileField(blank=True, null=True, upload_to='recetas')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
